### PR TITLE
minor tweaks based on test ride

### PR DESCRIPTION
**Pull request by geeksville**

### CODE REVIEW

**Comment by geeksville** [comment]
@casainho do the following two things work correctly on the 850C new_design branch?  I bet it is something I messed up in the sw102 port, but I thought I'd ask before digging around.

* BUG: Soc is wrong on bike, debug in simulator (starts at 0% SOC and goes up to 200% after 20% of battery consumed)
* BUG: walk assist power boost is way too low

**Comment by casainho** [comment]
Yes it works. Maybe it is your fieldPrintf printing one more zero?

Is SOC based on battery voltage or Coloumb counting? if the later, make sure void l2_calc_wh(void) is called at right frequency...

**Comment by geeksville** [comment]
The SOC based on voltage is fine (though of course based on voltage so 'meh' ;-) ).  The SOC based on coloumb counting hast the problem.  thanks I'll poke around.

And walk assist works fine on the 850C also?

**Comment by casainho** [comment]
So I would say you are calculating the l2_calc_wh 10x faster.

Yes, walk assist works well.

**Comment by geeksville** [comment]
@casainho cool beans!  thx.

**Pull request merged**
