### PR TITLE
WIP pull-request

### PR DESCRIPTION
**Pull request by geeksville**
I didn't fold all these commits into one megacommit (though I could if you want) so you could see the history of these WIP work items.  

Please see https://github.com/geeksville/SW102_LCD_Bluetooth/blob/khwip/TODO.md to see my take on the remaining queue of tasks.

Any feedback or coding would be welcome.  Especially appreciated would be
trying this on a display that is connected to a motor (because it will be
a few days before I can do that)

Note: in the current main.c you will want to comment out configscreen_show()
and instead call mainscreen_show()

  // mainscreen_show();
  configscreen_show();

### CODE REVIEW

**Comment by geeksville** [comment]
(attn @lowPerformer  and @casainho )

**Comment by geeksville** [comment]
btw - I'll just keep pushing my WIP changes to this branch until you think this PR is ready to merge.  Then I'll start more atomic PRs.

**Comment by lowPerformer** [comment]
Hell! Quite fast-paced ;)
Just galloped over your TODO. I can have a look in the "ISR RX buffer" thing. I also had this in mind but thought 100 ms would be enough to decode the buffer until next refresh. I want to keep the code as lean as possible.
btw:
What was your intention to use FDS?

Unfortunately I am not in my shack this weekend. But I give this a try next week.

**Comment by geeksville** [comment]
yep - I'm using FDS now and it seems to work well (and FDS automic update
means they basically solve the standard 'flash crc/flipflop settings' dance)

**Comment by geeksville** [comment]
@lowPerformer btw - I might have slightly busted your Makefile on Windows.  The commented out defines for openocd should make it clear what needs changing.  I just haven't gotten around to looking for an env var we can check for to conditionalize those three vars for windows vs linux.

**Comment by lowPerformer** [comment]
It was not compiling in the beginning. Have to remove the -Werror flag in Makefile or Eclipse aborts at first Warning. It also always wants to start openOCD no matter which target I start (I am working with Build Targets in Eclipse). This is because in Eclipse project settings -> C++ Build -> Builder Setting, there is a "flash_program" in the command line. Set this back to "default". Sure, also had to uncomment the Windows openOCD settings in Makefile.
With this minor fixes it seems to compile under Windows again. It is also programming and SW102 is showing "something" ;). Sorry I can't dig deeper this weekend :(

nrf SDK also detects the OS and calls appropriate Makefile. The magic sits somewhere in nRF5_SDK_12.3.0\components\toolchain\gcc. I see a "PLATFORM_SUFFIX := $(if $(filter Windows%,$(OS)),windows,posix)" in the Makefile.common line 11.

**Comment by geeksville** [comment]
ooh - thanks for the ptr to their OS check.

re: -Werror
Hmm - I wonder if your gcc version is different from mine?  I have Werror
on because there are no warnings now (at least for gcc version 4.9.3
20150529)

**Comment by lowPerformer** [comment]
It is the same with 5.4 and 7q2. but isn't this flag supposed to do this, throw warnings as errors?
Maybe 4.9.3 don't knows it and ignores it.

**Comment by geeksville** [comment]
-Werror means "convert warnings to errors" which I'm kinda a fan of,
because it bums me out that I end up debugging something on an embedded
target and only then do I realize my compiler had been warning me about the
cause but I hadn't noticed (i.e. falling off the end of arrays etc...)

I guess our different versions of GCC are more aggressive on noticing
things to warn about.

**Comment by geeksville** [comment]
btw - I fixed a fair number of bugs in my menu stuff (and there are still more to be fixed ;-)) since this PR, so the next time you run the code, you should probably pull from my WIP branch.

**Pull request merged**
