### PR TITLE
Another WIP PR - you guys will want this before editing config values

### PR DESCRIPTION
**Pull request by geeksville**
I fixed various things from the TODO list.  See comments in the commits.

### CODE REVIEW

**Comment by casainho** [comment]
Can you please make some photos and maybe a short video of the configurations screen working on current state? I would like to share on forum for others see.

**Comment by geeksville** [comment]
@casainho sure, here's a little youtube I just made (with some audio description). This is my sort of hacked up dev unit.  I'll take some picts of a prettier one after I put it on my bike tomorrow.

[https://www.youtube.com/watch?v=zIf8hCtIuJI](url)

**Comment by geeksville** [comment]
@casainho make sure to point people to the TODO list so they understand the UX will be prettier before the beta (less white backgrounds, using the battery graphic for SOC etc...)

**Comment by casainho** [comment]
Hmm, can you force a low and fixed light on you camera so everything will be darker and we can clearly see the pixels/what is on LCD?

If you are using an Android phone, you can use Open Camera to fix and force the amount of light.

thank you.

**Comment by casainho** [comment]
I can see sections on configurations menu and seems to work great!!

Some questions:
- can't the font be smaller on each item name? only for being possible to show longer names... would this be good?
- can't visually differentiate each item, I think an horizontal line between each item could be good

**Comment by geeksville** [comment]
I agree - a horizontal line is needed between each entry.  Also, the
heading on each of the menus should be rendered in black (instead of white)
but with a double thick white line underneath.

re: font size
alas - the font I'm using for each of the menu entries is already only
5x12.  But good point, after doing some other stuff I'll try changing it to
the only stock font that ugui provides that is narrower (4x6).

**Comment by geeksville** [comment]
hmm - I just tried a quick the 4x6 font (you can pull it to your workspace
if you want).  I think it might be too small.  Possibly going back to 5x12
is right but with smarter breaking the strings only at whitespace when
wrapping...

**Pull request merged**
